### ISSUE TITLE
Sweeten binds between observers and observables

### ISSUE THREAD

**Issue by sebastianvarela** [RxSwiftCommunity/RxSwiftExt#244]
### Name and description
After several years working with ReactiveSwift now we have a long-term project that use RxSwift. The first thing I miss is the binding operator for observables/observer.

When someone want to bind an `observer` to an `observable` have to do something like this:
```swift
observable
    .bind(to: observer)
    .disposed(by: disposeBag)
```

I made an extension that create two operators to link observer-observable-disposebag:
```swift
func += <T: DisposableContainer>(container: T, disposable: Disposable) -> T
func <~ <Destination: ObserverType, Source: ObservableConvertibleType>(observer: Destination, observable: Source) -> Disposable where Source.Element == Destination.Element
func ~> <Destination: ObserverType, Source: ObservableConvertibleType>(observable: Source, observer: Destination) -> Disposable where Source.Element == Destination.Element
```
### Motivation for inclusion
When you use MVVM, for example, and you have a lot of binding inside a func, this operator improve the legibility of the code by removing all the boilerplate.

### Example of use
```swift
disposeBag += observer ~> observable
``` 
or
```swift
disposeBag += observable <~ observer
```

You can also use a closure or a func to just observe an observable by using:
```swift
disposeBag += observable ~> { value in
    // Do something with value
}
```
or 
```swift
func updateValue(value: Any) {
    // Do something with value
}
disposeBag += observable ~> updateValue
```

**Comment by MortyMerr** [comment]
I am strongly against this proposal.
It doesn’t bring any value, just allows to implement things in another way. It’s obviously just a wrapper around existing methods. They will be confusing for new user. 
They are not express “drive/bind/emit” behavior of different traits.
This “sweetness” is subjective. I don’t think this these operators are more readable. As I know RxSwift already had similar operators long time ago, but they were removed.
Operators should not be added just because of personal preferences or because they are defined in ReactiveSwift. It’s a separate project.
You can declare these operators locally, but I don’t see any pros in contributing them to community. Even in Ext.
Sincerely

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
I see the point and I agree with you @MortyMerr, but in my opinion the way you wrote this message seems harsh and unwelcoming. Even though I don't make this proposal, I felt uncomfortable reading your answer. 😅😅

**Comment by MortyMerr** [comment]
@jdisho lol 😅 My message is just arguments 😀 What do you want me to do with it? Add an emoji after each sentence? 😊

**Comment by jdisho** [comment]
I think it would be great to show some kindness and appreciation, **at least** for the time 
invested to make a proposal (as an issue or pull-request). 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freak4pc** [comment]
Leaving the sentiments and appreciation for the code aside, I also agree that whatever value this PR would bring is not universal enough to share in this repo (personal opinion of course).

Custom operators are a touchy subject, too many people are entirely against it, and they're very easy to make. So I think people who are _for_ this usually just add them, so it doesn't justify adding here regardless of the time put into making the suggestion.

**Comment by jdisho** [comment]
I suppose we can close this issue.
