### ISSUE TITLE
combineLatest(o1: Observable, o2: Observable)

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxSwiftExt#33]
### Name and description

`combineLatest(o1, o2)` takes in two ObservableType types of types Observable<T> and Observable<U> and combines them into a single ObservableType<(T, U)>

### Motivation for inclusion

I found myself (few times already) producing a combination of several inputs in my app's UI, e.g. a search bar and a toggle bar item. However I always have few bindings to bind that input to so I end up creating a combined observable that shares replay and then subscribe multiple times to it 

I think it's gonna be easier to be able to avoid providing a closure to `combineLatest` and just bundle together all the inputs, so one can subscribe multiple times afterwards

PS: It might be nicer to allow the existing `combineLatest` operator to take a `nil` parameter for its closure parameter and in that case just bundle up the inputs as a tuple but that would mean a change in RxSwift itself vs. a custom operator in RxSwift-Ext

Maybe @kzaher could chime in with some argumentation if that'd make for a main repo patch or it doesn't make sense to?

### Example of use

```swift
let input = Observable.combineLatest(searchBar.rx_text, segmented.rx_value).shareReplay(1)

input.
   .map {input in NSURL(string: "...blah blah blah use input blah")!}
   .flatMapLatest {url in
      NSURLSession.sharedSession().rx_JSON(url)
   } ... etc. etc.

input.
   .subscribeNext {search, selectedIndex in 
       ... refresh table view blah blah blah ...
   }
```

**Comment by kzaher** [comment]
I think that @ashfurrow asked me once about this.

I thought that this could create ambiguity problems with Swift compiler because we previously had that API defined little differently, and I thought it would make sense for this to be required because if you are using tuples, that will probably be followed by a `map` operator soon after that to create something out of that tuple.

I guess if you all guys want it to have default value for resultSelector, I guess we can add those default values to that main repo and keep things simpler.

**Comment by icanzilb** [comment]
Since this has been re-assigned I'm going to close it in this repo, thanks for the feedback everyone
